apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-identity-webhook
  namespace: kube-system
webhooks:
- name: pod-identity-webhook.amazonaws.com
  failurePolicy: Ignore
  clientConfig:
    service:
      name: pod-identity-webhook
      namespace: kube-system
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVUWJ6SitGNE9wOUlTZGZRaVBrRGV5cXZTaTZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tjRzlrTFdsa1pXNTBhWFI1TFhkbFltaHZiMnN1YTNWaVpTMXplWE4wWlcwdQpjM1pqTUI0WERUSXdNRGN5T0RFNU5ESXhNVm9YRFRJeE1EY3lPREU1TkRJeE1Wb3dMekV0TUNzR0ExVUVBd3drCmNHOWtMV2xrWlc1MGFYUjVMWGRsWW1odmIyc3VhM1ZpWlMxemVYTjBaVzB1YzNaak1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXQ2ajdXcHNBR3dyaTVkdDM3a3VVNDJVWmkrVE1WWGd5UGNiVAp6bGZIRmRpU2xqUlBQOGhtbHU5UXZrUDBWZFRTQkFjeXVRdVNlTDVTV2VPZnYwdnJYM2hZWCtOWmlYVVpqNWEvCmFlWUxZMHZyc1hIY1JSYU1nQWNvcVdHb2VoYmZXWHorTWJnZEhLM3FiN0I3VFlxV0NVaVZRdERHNVc5aVRLSmkKTXd3M1gzcmtwQ3NBK2lnTjdzTzBRZWpOOTdDdDlqbGFWY1ltbThyZlFvTmRTSHlhZTl6YmpTVmNwZEdYR252QwpZMTZDUzNqNDJUaXhYVG9maWluZGY3UWRGZmJKSzBhS3JlY3NvdytUR3FmNEpHS01haEhoUjZPVTk3c2JvWHQvClJiY2JUMVo2OVRCY1Fxam9zSHBsRllqazYvYWk0aFhwTGR2cjVvNDZrSFJkK1REQkhRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVQjNpTFR1ZE5keWczNUlrRjNBNlRoMGF4d2Zjd0h3WURWUjBqQkJnd0ZvQVVCM2lMVHVkTgpkeWczNUlrRjNBNlRoMGF4d2Zjd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFKZ1FnMTdUa1haQXN6UExTcVYxTFQ5QXJYRVAzdHlCQ1d3UWxhb3RUYmlDUmNscDR0b0ZhaFZaaERncC8KTmc2MzhUWWpxQlp4UmRiK0VjdXRKZysxNm4zWVRiUWUyWTZMMjVaRUNzTGk3SjhicjJzU1JncUZhbUpTYkpreApFbkdBWjMyaWVWTzlVcEs1T0YzU3o1VVBPUHRSUytTanpTYmlZZXhmSktuWGRWd3Q5dDFTM3Jlc3NwNURQUGJxCjZ5TkdYR0s4VkRnckVSWEVqV1VtWnRzRCtnZ213dENlbHYxd01xZ0V3cnhYMHFNbnZGQnlsdHRlYW1tZ0lzaFIKdC83N0NjdkJxdTdaRVY3RkNwMjFBSlFJTEpLSVZzaXBQTG5ZL3hSSGthcHRHUDFuMEhiaEQrQlMrN3ZldEg3eAp0ZWxIYy9HbUtMVUdmMzhZSXhTS3RsQU9wdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]